// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetworkMonitoringSystem.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NetworkMonitoringSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MonitoringDbContext))]
    [Migration("20261009122055_AddResourceMetrics")]
    partial class AddResourceMetrics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NetworkMonitoringSystem.Domain.Devices.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AgentKeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HostName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MonitoringMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("HostName");

                    b.HasIndex("Name");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("NetworkMonitoringSystem.Domain.Monitoring.DeviceSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("CpuUsagePercent")
                        .HasColumnType("double precision");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasResources")
                        .HasColumnType("boolean");

                    b.Property<long?>("MemoryTotalBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("MemoryUsedBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "RecordedAt");

                    b.ToTable("DeviceSnapshots");
                });

            modelBuilder.Entity("NetworkMonitoringSystem.Domain.Monitoring.DiskUsage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FreeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("SnapshotId")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("DiskSnapshots", (string)null);
                });

            modelBuilder.Entity("NetworkMonitoringSystem.Domain.Monitoring.MonitoringEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("OccurredAt");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("NetworkMonitoringSystem.Domain.Monitoring.MonitoringSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("OfflineAfterMissedSyncs")
                        .HasColumnType("integer");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("integer");

                    b.Property<int>("SyncIntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("TopProcessCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MonitoringSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OfflineAfterMissedSyncs = 3,
                            RetentionDays = 30,
                            SyncIntervalSeconds = 60,
                            TopProcessCount = 10
                        });
                });

            modelBuilder.Entity("NetworkMonitoringSystem.Domain.Monitoring.NetworkInterfaceUsage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BytesReceived")
                        .HasColumnType("bigint");

                    b.Property<long>("BytesSent")
                        .HasColumnType("bigint");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsUp")
                        .HasColumnType("boolean");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("SnapshotId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("NetworkInterfaceSnapshots", (string)null);
                });

            modelBuilder.Entity("NetworkMonitoringSystem.Domain.Monitoring.Outage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "StartedAt");

                    b.ToTable("Outages");
                });

            modelBuilder.Entity("NetworkMonitoringSystem.Domain.Monitoring.DeviceSnapshot", b =>
                {
                    b.HasOne("NetworkMonitoringSystem.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NetworkMonitoringSystem.Domain.Monitoring.DiskUsage", b =>
                {
                    b.HasOne("NetworkMonitoringSystem.Domain.Monitoring.DeviceSnapshot", null)
                        .WithMany("Disks")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NetworkMonitoringSystem.Domain.Monitoring.MonitoringEvent", b =>
                {
                    b.HasOne("NetworkMonitoringSystem.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("NetworkMonitoringSystem.Domain.Monitoring.NetworkInterfaceUsage", b =>
                {
                    b.HasOne("NetworkMonitoringSystem.Domain.Monitoring.DeviceSnapshot", null)
                        .WithMany("NetworkInterfaces")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NetworkMonitoringSystem.Domain.Monitoring.Outage", b =>
                {
                    b.HasOne("NetworkMonitoringSystem.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NetworkMonitoringSystem.Domain.Monitoring.DeviceSnapshot", b =>
                {
                    b.Navigation("Disks");

                    b.Navigation("NetworkInterfaces");
                });
#pragma warning restore 612, 618
        }
    }
}
