// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetworkMonitoringSystem.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NetworkMonitoringSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MonitoringDbContext))]
    [Migration("20261009110445_AddAgentIdentity")]
    partial class AddAgentIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NetworkMonitoringSystem.Domain.Devices.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AgentKeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HostName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MonitoringMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("HostName");

                    b.HasIndex("Name");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("NetworkMonitoringSystem.Domain.Monitoring.MonitoringSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("OfflineAfterMissedSyncs")
                        .HasColumnType("integer");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("integer");

                    b.Property<int>("SyncIntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("TopProcessCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MonitoringSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OfflineAfterMissedSyncs = 3,
                            RetentionDays = 30,
                            SyncIntervalSeconds = 60,
                            TopProcessCount = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
